# Generated by Django 6.0.3 on 2026-03-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='included_pos',
            field=models.ManyToManyField(blank=True, related_name='schedules_included', to='scheduling.pointofsale'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='included_promoters',
            field=models.ManyToManyField(blank=True, related_name='schedules_included', to='scheduling.promoter'),
        ),
    ]
